server:
  port: 8080

spring:
  profiles:
    active: dev
  datasource:
    druid:
      driver-class-name: ${ai.datasource.driver-class-name}
      url: jdbc:mysql://${ai.datasource.host}:${ai.datasource.port}/${ai.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${ai.datasource.username}
      password: ${ai.datasource.password}
  redis:
    host: ${ai.redis.host}
    port: ${ai.redis.port}
    password: ${ai.redis.password}
    database: ${ai.redis.database}
  servlet:
    multipart:
      max-file-size: ${ai.servlet.multipart.max-file-size}
      max-request-size: ${ai.servlet.multipart.max-request-size}

ali:
  oss:
    access-key-id: ${ai.ali.oss.access-key-id}
    access-key-secret: ${ai.ali.oss.access-key-secret}
    bucket-name: ${ai.ali.oss.bucket-name}
    end-point: ${ai.ali.oss.end-point}
    region: ${ai.ali.oss.region}
  ssm:
    access-key-id: ${ai.ali.ssm.access-key-id}
    access-key-secret: ${ai.ali.ssm.access-key-secret}
    end-point: ${ai.ali.ssm.end-point}
    regionId: ${ai.ali.ssm.regionId}
    signName: ${ai.ali.ssm.signName}
    templateCode: ${ai.ali.ssm.templateCode}
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ai.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true
image:
  localPath: ${ai.image.localPath}
logging:
  level:
    com:
      ai:
        mapper: debug
        service: debug
        controller: debug
debug: true
jwt:
  # 设置jwt签名加密时使用的秘钥
  user-secret-key: ${ai.jwt.user-secret-key}
  # 设置jwt过期时间
  user-ttl: ${ai.jwt.user-ttl}
  # 设置前端传递过来的令牌名称
  user-token-name: ${ai.jwt.user-token-name}
